# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2


references:

  container: &container
    docker:
      - image: circleci/node:8.10.0
    working_dir: ~/project

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

jobs:

  checkout_code:
    <<: *container
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project

  deploy:
    <<: *container
    steps:
      - *restore_repo
      - run:
          name: Deploy
          command: |
            npm install reveal-md
            ~/node_modules/bin/reveal-md


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - checkout_code
      - deploy:
          requires:
            - checkout_code
          filters:
            branches:
              only: master
